using System;
using System.IO;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEditor.Build.Reporting;

[InitializeOnLoad] public static class ShopAutomation {
    static string Evidence=>Path.GetFullPath(Path.Combine(Application.dataPath,"../evidence"));
    static double start;static int errors;static List<DayReport> days=new List<DayReport>();static bool shelfPlacement,productPlacement,inventory=true,pickupBeforeRevenue,actors,clock,visualCaptured;
    static ShopAutomation(){if(SessionState.GetBool("ShopTestV2",false)){EditorApplication.update+=Observe;Application.logMessageReceived+=Log;}}
    static void Log(string m,string trace,LogType t){if(t==LogType.Exception||t==LogType.Error||t==LogType.Assert)errors++;}
    public static void CreateAndPlay(){Directory.CreateDirectory(Evidence);Directory.CreateDirectory("Assets/Scenes");Directory.CreateDirectory("Assets/Materials");EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);
        var camera=new GameObject("Main Camera").AddComponent<Camera>();camera.tag="MainCamera";camera.orthographic=true;camera.orthographicSize=6.8f;camera.transform.position=new Vector3(13,18,-21);camera.transform.LookAt(new Vector3(0,.3f,-1.5f));camera.rect=new Rect(0,.13f,1,.77f);camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(.77f,.9f,.88f);camera.nearClipPlane=.1f;camera.farClipPlane=80;
        var light=new GameObject("Sunlight").AddComponent<Light>();light.type=LightType.Directional;light.intensity=.8f;light.transform.rotation=Quaternion.Euler(55,-30,0);light.shadows=LightShadows.Soft;RenderSettings.ambientMode=UnityEngine.Rendering.AmbientMode.Flat;RenderSettings.ambientLight=new Color(.42f,.45f,.48f);
        Color[] colors={new Color(.48f,.72f,.49f),new Color(.86f,.82f,.68f),new Color(.4f,.46f,.5f),new Color(.75f,.8f,.76f),new Color(.98f,.97f,.91f),new Color(1,.71f,.32f),new Color(.94f,.44f,.37f),new Color(.35f,.72f,.85f),new Color(.69f,.5f,.8f),new Color(.47f,.72f,.54f),new Color(.22f,.59f,.49f),new Color(.68f,.8f,.82f),new Color(.71f,.57f,.4f),new Color(.24f,.3f,.32f),new Color(.84f,.75f,.61f),new Color(1,.82f,.65f)};
        var root=new GameObject("Konbini");var view=root.AddComponent<StoreView>();view.cameraView=camera;view.japanese=AssetDatabase.LoadAssetAtPath<Font>("Assets/Fonts/NotoSansCJKjp-Regular.otf");if(!view.japanese)throw new Exception("Japanese font not imported");view.materials=new Material[colors.Length];for(int i=0;i<colors.Length;i++){string file="Assets/Materials/Town"+i+".mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(file);if(!mat){mat=new Material(Shader.Find("Standard"));AssetDatabase.CreateAsset(mat,file);}mat.color=colors[i];mat.SetFloat("_Glossiness",.05f);view.materials[i]=mat;}
        var game=root.AddComponent<KonbiniGame>();game.view=view;view.Build(new StoreSimulation(new ShopModel(42),42));EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene(),"Assets/Scenes/SmallKonbini.unity");EditorBuildSettings.scenes=new[]{new EditorBuildSettingsScene("Assets/Scenes/SmallKonbini.unity",true)};PlayerSettings.companyName="Local Lab";PlayerSettings.productName="ちいさなコンビニ";PlayerSettings.defaultWebScreenWidth=1200;PlayerSettings.defaultWebScreenHeight=720;PlayerSettings.runInBackground=true;AssetDatabase.SaveAssets();Balance();StoreChecks();ResultsChecks();ForecastChecks();CheckStaffBalance();start=EditorApplication.timeSinceStartup;Application.logMessageReceived+=Log;EditorApplication.update+=Begin;
    }
    static void Begin(){if(EditorApplication.timeSinceStartup-start<5||EditorApplication.isCompiling||EditorApplication.isUpdating)return;EditorApplication.update-=Begin;SessionState.SetBool("ShopTestV2",true);SessionState.SetFloat("ShopStartV2",(float)EditorApplication.timeSinceStartup);EditorApplication.update+=Observe;EditorApplication.EnterPlaymode();}
    static void Capture(KonbiniGame game){var camera=game.view.cameraView;var previous=camera.targetTexture;var rect=camera.rect;var rt=new RenderTexture(1200,720,24);camera.targetTexture=rt;camera.rect=new Rect(0,0,1,1);camera.Render();RenderTexture.active=rt;var tex=new Texture2D(1200,720,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1200,720),0,0);tex.Apply();File.WriteAllBytes(Path.Combine(Evidence,"editor-town-v4.png"),tex.EncodeToPNG());camera.targetTexture=previous;camera.rect=rect;RenderTexture.active=null;UnityEngine.Object.DestroyImmediate(rt);UnityEngine.Object.DestroyImmediate(tex);}
    static void Observe(){if(!EditorApplication.isPlaying)return;var game=UnityEngine.Object.FindAnyObjectByType<KonbiniGame>();if(!game)return;var sim=game.store;
        if(game.model.state=="Morning"){
            if(game.model.day==1){game.model=new ShopModel(42);sim.model=game.model;int initial=sim.shelves[0].slot;sim.Place(0,7);shelfPlacement=sim.shelves[0].slot==7;sim.Place(0,initial);productPlacement=sim.Assign(5,2)&&sim.shelves[5].product==2;}
            int[] target=game.model.day==1?new[]{22,12,38,16,6}:new[]{18,10,32,16,5};for(int i=0;i<5;i++)game.model.order[i]=Math.Max(0,target[i]-game.model.stock[i]);for(int i=0;i<5;i++)game.model.price[i]=game.model.day==3?3:1;while(game.model.OrderCost()>game.model.cash){for(int i=0;i<5;i++)if(game.model.order[i]>0)game.model.order[i]--;}game.SetStaff(game.model.day==2||game.model.day==6?2:1);sim.speed=game.model.day==1?1:4;game.Open();
        }
        else if(game.model.state=="Open"){
            inventory&=sim.InventoryMatches();actors|=sim.customers.Exists(c=>c.body&&c.body.GetComponentInChildren<Renderer>()!=null)&&game.view.clerk!=null;clock|=sim.Clock()!="08:00";pickupBeforeRevenue|=sim.pickups>0&&sim.checkouts==0&&game.model.report.revenue==0;
            if(!visualCaptured&&sim.elapsed>14){Capture(game);visualCaptured=true;}
        }
        else if(game.model.state=="Result"){days.Add(game.model.report);File.WriteAllText(Path.Combine(Evidence,"editor-progress-v4.json"),JsonUtility.ToJson(game.Sample(),true));Debug.Log("SHOP_V2_DAY "+game.model.day+" revenue="+game.model.report.revenue+" restocks="+sim.restocks);game.Next();}
        else if(game.model.state=="Final"){
            var final=game.Sample();bool ledger=game.model.cash+game.model.InventoryValue()-30000==game.model.totalProfit;bool passed=game.history.Count==7&&days.Count==7&&actors&&clock&&inventory&&pickupBeforeRevenue&&shelfPlacement&&productPlacement&&sim.moved>0&&sim.staffMoves>0&&sim.restocks>0&&sim.waitingFrames>0&&sim.checkouts==game.model.totalSold&&sim.maxQueue<=4&&game.model.totalWaste>0&&game.model.totalMissed>0&&game.model.totalElectricity==2100&&ledger&&game.model.totalLabor==7*ShopModel.BaseLabor+game.model.twoStaffDays*ShopModel.ExtraLabor&&game.model.twoStaffDays==2&&sim.parallelFrames>0&&game.history.TrueForAll(d=>d.forecast!=null&&d.forecast.staffCount==d.staffCount)&&errors==0;game.Retry();bool retry=game.model.day==1&&game.model.cash==30000&&game.model.totalSold==0&&game.model.state=="Morning"&&game.history.Count==0;File.WriteAllText(Path.Combine(Evidence,"editor-play-v4.json"),JsonUtility.ToJson(new PlayResult{passed=passed&&retry,consoleErrors=errors,ledger=ledger,retry=retry,inventory=inventory,actors=actors,clock=clock,pickupBeforeRevenue=pickupBeforeRevenue,shelfPlacement=shelfPlacement,productPlacement=productPlacement,elapsedSeconds=EditorApplication.timeSinceStartup-SessionState.GetFloat("ShopStartV2",0),days=days.ToArray(),final=final},true));SessionState.SetBool("ShopTestV2",false);EditorApplication.Exit(passed&&retry?0:1);
        }
        if(EditorApplication.timeSinceStartup-SessionState.GetFloat("ShopStartV2",0)>300){SessionState.SetBool("ShopTestV2",false);Debug.LogError("Shop V2 timeout");EditorApplication.Exit(2);}
    }
    [Serializable] class PlayResult{public bool passed,ledger,retry,inventory,actors,clock,pickupBeforeRevenue,shelfPlacement,productPlacement;public int consoleErrors;public double elapsedSeconds;public DayReport[] days;public KonbiniGame.Snapshot final;}
    static void StoreChecks(){var m=new ShopModel(7);m.weather=0;m.order[0]=24;m.order[1]=12;m.order[2]=30;var sim=new StoreSimulation(m,7);bool placement=sim.Place(0,7)&&sim.shelves[0].slot==7;bool duplicate=sim.Assign(5,2)&&sim.shelves[5].product==2;bool coldRestriction=!sim.Assign(2,4);bool open=sim.Open();bool locks=!sim.Place(0,2)&&!sim.Assign(0,3);bool inventory=sim.InventoryMatches();int available=sim.shelves[2].stock;sim.shelves[2].stock=0;sim.warehouse[2]+=available;int oldCash=m.cash;int decision=0;for(int n=0;n<10&&decision!=-1;n++)decision=m.Decide(2,false);bool shelfMiss=decision==-1&&m.report.shelfMissed>0&&m.cash==oldCash;sim.shelves[2].stock=available;sim.warehouse[2]-=available;int pickup=m.Decide(0,true);while(pickup!=1)pickup=m.Decide(0,true);sim.shelves[0].stock--;var reservation=new StoreSimulation.Shopper{product=0,carrying=true};sim.customers.Add(reservation);bool deferred=m.report.revenue==0&&sim.InventoryMatches();m.Checkout(0);reservation.carrying=false;bool committed=m.report.sold==1&&m.cash>oldCash&&sim.InventoryMatches();sim.customers.Clear();m.Close(sim.Electricity());bool ledger=m.cash+m.InventoryValue()-30000==m.totalProfit&&m.report.electricity==300;var result=new StoreTest{passed=placement&&duplicate&&coldRestriction&&open&&locks&&inventory&&shelfMiss&&deferred&&committed&&ledger,placement=placement,duplicate=duplicate,coldRestriction=coldRestriction,locks=locks,inventory=inventory,shelfMiss=shelfMiss,deferred=deferred,committed=committed,ledger=ledger};File.WriteAllText(Path.Combine(Evidence,"store-tests-v4.json"),JsonUtility.ToJson(result,true));if(!result.passed)throw new Exception("Store tests failed");}
    [Serializable] class StoreTest{public bool passed,placement,duplicate,coldRestriction,locks,inventory,shelfMiss,deferred,committed,ledger;}
    static void ForecastChecks(){
        var m=new ShopModel(99){weather=2};int[] order={22,12,38,16,6};Array.Copy(order,m.order,5);var sim=new StoreSimulation(m,99);sim.Assign(5,2);var reference=ForecastCalculator.Clone(sim,99);
        var f=ForecastCalculator.Calculate(sim);var again=ForecastCalculator.Calculate(sim);bool deterministic=JsonUtility.ToJson(f)==JsonUtility.ToJson(again);bool untouched=m.state=="Morning"&&m.cash==30000&&m.stock[0]==0&&m.order[2]==38&&sim.customers.Count==0;
        var two=ForecastCalculator.Calculate(sim,2);bool costs=two.labor-f.labor==ShopModel.ExtraLabor&&two.staffCount==2&&f.staffCount==1&&f.purchases==m.OrderCost();bool ranges=f.products.Length==5&&f.samples==24&&f.revenue.low<f.revenue.high;
        var actual=ForecastCalculator.Run(sim);var check=ForecastCalculator.Run(reference);bool rng=JsonUtility.ToJson(actual)==JsonUtility.ToJson(check);bool comparable=actual.products.Length==f.products.Length&&actual.revenue!=f.revenue.mean;
        var p=new ProductDayResult{product_id=0,opportunity_loss_count=1,waste_count=4};bool hint=ShopModel.Comment(p,1,0)=="在庫あり。棚補充が遅れた可能性";p.waste_count=0;p.shelf_loss_count=2;hint&=ShopModel.Comment(p,1,0)=="需要に対して仕入れが不足しました";p.opportunity_loss_count=0;p.units_sold=0;hint&=ShopModel.Comment(p,3,5)=="販売なし。仕入れ・陳列を確認";
        bool passed=deterministic&&untouched&&costs&&ranges&&rng&&comparable&&hint;File.WriteAllText(Path.Combine(Evidence,"forecast-tests.json"),"{\"passed\":"+passed.ToString().ToLowerInvariant()+",\"deterministic\":"+deterministic.ToString().ToLowerInvariant()+",\"untouched\":"+untouched.ToString().ToLowerInvariant()+",\"costs\":"+costs.ToString().ToLowerInvariant()+",\"ranges\":"+ranges.ToString().ToLowerInvariant()+",\"rngUnchanged\":"+rng.ToString().ToLowerInvariant()+",\"notExact\":"+comparable.ToString().ToLowerInvariant()+",\"hints\":"+hint.ToString().ToLowerInvariant()+"}");if(!passed)throw new Exception("Forecast checks failed");
    }
    [Serializable] public class StaffCase {public int seed,weather,staff,price,policy,revenue,sold,missed,waste,labor,profit,restocks;}
    public static void VerifyDailyForecast(){Directory.CreateDirectory(Evidence);ResultsChecks();ForecastChecks();}
    [Serializable] class StaffCases {public int count;public StaffCase[] cases;}
    public static void CheckLowStaff(){Directory.CreateDirectory(Evidence);var cases=new List<StaffCase>();for(int seed=101;seed<=140;seed++)for(int staff=1;staff<=2;staff++){
        var m=new ShopModel(seed){cash=100000,weather=3,staffCount=staff};for(int i=0;i<5;i++){m.price[i]=3;m.order[i]=(int)Math.Ceiling(m.Demand(i)*.85f);}var sim=new StoreSimulation(m,seed);sim.Assign(5,2);var r=ForecastCalculator.Run(sim,.04f);cases.Add(new StaffCase{seed=seed,weather=3,staff=staff,price=3,policy=1,revenue=r.revenue,sold=r.sold,missed=r.missed,waste=r.waste,labor=r.laborCost,profit=r.profit,restocks=sim.restocks});
    }File.WriteAllText(Path.Combine(Evidence,"staff-low.json"),JsonUtility.ToJson(new StaffCases{count=cases.Count,cases=cases.ToArray()},true));}
    public static void CheckStaffHoldout(){Directory.CreateDirectory(Evidence);var cases=new List<StaffCase>();foreach(int weather in new[]{3,0,2})for(int seed=101;seed<=140;seed++)for(int staff=1;staff<=2;staff++){
        var m=new ShopModel(seed){cash=100000,weather=weather,staffCount=staff};for(int i=0;i<5;i++)m.order[i]=(int)Math.Ceiling(m.Demand(i)*.85f);var sim=new StoreSimulation(m,seed);sim.Assign(5,2);var r=ForecastCalculator.Run(sim,.04f);cases.Add(new StaffCase{seed=seed,weather=weather,staff=staff,price=1,policy=1,revenue=r.revenue,sold=r.sold,missed=r.missed,waste=r.waste,labor=r.laborCost,profit=r.profit,restocks=sim.restocks});
    }File.WriteAllText(Path.Combine(Evidence,"staff-holdout.json"),JsonUtility.ToJson(new StaffCases{count=cases.Count,cases=cases.ToArray()},true));}
    public static void CheckStaffBalance(){Directory.CreateDirectory(Evidence);var cases=new List<StaffCase>();foreach(int weather in new[]{3,0,2})for(int seed=1;seed<=10;seed++)for(int staff=1;staff<=2;staff++)for(int price=0;price<4;price++)for(int policy=0;policy<3;policy++){
        var m=new ShopModel(seed){cash=100000,weather=weather,staffCount=staff};for(int i=0;i<5;i++){m.price[i]=price;m.order[i]=policy==0?2:policy==2?ShopModel.Products[i].maxDaily*2:(int)Math.Ceiling(m.Demand(i)*.85f);}var sim=new StoreSimulation(m,seed);sim.Assign(5,2);var r=ForecastCalculator.Run(sim,.04f);if(m.cash+m.InventoryValue()-100000!=r.profit)throw new Exception("Staff accounting mismatch");cases.Add(new StaffCase{seed=seed,weather=weather,staff=staff,price=price,policy=policy,revenue=r.revenue,sold=r.sold,missed=r.missed,waste=r.waste,labor=r.laborCost,profit=r.profit,restocks=sim.restocks});
    }File.WriteAllText(Path.Combine(Evidence,"staff-balance.json"),JsonUtility.ToJson(new StaffCases{count=cases.Count,cases=cases.ToArray()},true));Debug.Log("STAFF_BALANCE "+cases.Count);}
    static void ResultsChecks(){
        var m=new ShopModel(42);m.order[0]=5;m.order[2]=8;m.price[0]=0;m.price[2]=0;m.Open();m.Checkout(0);m.Checkout(2);m.Decide(3,false);m.Close(300);var r=m.report;
        bool fields=r.products.Length==5&&r.products[0].day==1&&r.products[0].product_id==0&&r.products[0].units_sold==1&&r.products[0].revenue==128&&r.products[0].waste_count==4&&r.products[0].ending_stock==0&&r.products[2].ending_stock==7&&r.products[3].opportunity_loss_count==1&&r.products[3].sold_out&&!r.products[4].sold_out;
        int sold=0,revenue=0,waste=0,missed=0;foreach(var p in r.products){sold+=p.units_sold;revenue+=p.revenue;waste+=p.waste_count;missed+=p.opportunity_loss_count;}bool sums=sold==r.sold&&revenue==r.revenue&&waste==r.waste&&missed==r.missed;
        string saved=JsonUtility.ToJson(r);m.Next();m.price[0]=3;m.order[0]=1;m.Open();m.Checkout(0);m.Close();bool immutable=saved==JsonUtility.ToJson(r)&&m.report.products[0].revenue==224;
        var p0=new ProductDayResult{product_id=2,units_sold=1,ending_stock=8};bool comments=ShopModel.Comment(p0,1,0)=="在庫が多く残っています"&&ShopModel.Comment(p0,3,5)=="価格が高すぎる可能性があります";p0.waste_count=2;comments&=ShopModel.Comment(p0,1,0)=="仕入れ過多の可能性があります";p0.opportunity_loss_count=4;comments&=ShopModel.Comment(p0,1,0)=="在庫あり。棚補充が遅れた可能性";
        bool passed=fields&&sums&&immutable&&comments;File.WriteAllText(Path.Combine(Evidence,"daily-results-tests.json"),"{\"passed\":"+passed.ToString().ToLowerInvariant()+",\"fields\":"+fields.ToString().ToLowerInvariant()+",\"sums\":"+sums.ToString().ToLowerInvariant()+",\"immutable\":"+immutable.ToString().ToLowerInvariant()+",\"comments\":"+comments.ToString().ToLowerInvariant()+"}");if(!passed)throw new Exception("Daily results checks failed");
    }
    static ShopModel Sim(int seed,int price,int weather,int stock){var m=new ShopModel(seed);m.weather=weather;for(int i=0;i<5;i++){m.price[i]=price;m.order[i]=stock;}m.cash=100000;m.Open();int visits=m.VisitCount();for(int n=0;n<visits;n++){int p=m.Candidate();if(p>=0)m.Buy(p);}m.Close();return m;}
    public static void Balance(){var r=new BalanceResult();for(int s=1;s<=300;s++){var low=Sim(s,0,0,60);var normal=Sim(s,1,0,60);var high=Sim(s,3,0,60);var hot=Sim(s,1,2,60);var lowStock=Sim(s,1,0,1);var excessive=Sim(s,1,0,60);r.lowSales+=low.report.sold;r.normalSales+=normal.report.sold;r.highSales+=high.report.sold;r.mildDrinks+=normal.report.sales[2];r.hotDrinks+=hot.report.sales[2];r.shortageMisses+=lowStock.report.missed;r.fullMisses+=normal.report.missed;r.excessWaste+=excessive.report.waste;r.shortageWaste+=lowStock.report.waste;var a=new ShopModel(s);var b=new ShopModel(s);for(int d=0;d<7;d++){for(int i=0;i<5;i++){a.order[i]=Math.Max(0,(int)(a.Demand(i)*.9f)-a.stock[i]);b.order[i]=ShopModel.Products[i].maxDaily*2;}while(b.OrderCost()>b.cash){bool changed=false;for(int i=0;i<5;i++)if(b.order[i]>0){b.order[i]--;changed=true;}if(!changed)break;}a.Open();b.Open();int av=a.VisitCount(),bv=b.VisitCount();for(int n=0;n<av;n++){int p=a.Candidate();if(p>=0)a.Buy(p);}for(int n=0;n<bv;n++){int p=b.Candidate();if(p>=0)b.Buy(p);}a.Close();b.Close();a.Next();b.Next();}r.targetedProfit+=a.totalProfit;r.maxOrderProfit+=b.totalProfit;}
        var edge=new ShopModel(5);for(int i=0;i<5;i++)edge.order[i]=80;r.overBudgetBlocked=!edge.Open()&&edge.cash==30000;edge=new ShopModel(2);edge.order[2]=4;edge.order[0]=5;edge.Open();edge.Close();r.carryover=edge.stock[2]==4&&edge.stock[0]==0;r.accounting=edge.cash+edge.InventoryValue()-30000==edge.totalProfit;r.passed=r.lowSales>r.normalSales&&r.normalSales>r.highSales&&r.hotDrinks>r.mildDrinks&&r.shortageMisses>r.fullMisses&&r.excessWaste>r.shortageWaste&&r.targetedProfit>r.maxOrderProfit&&r.overBudgetBlocked&&r.carryover&&r.accounting;File.WriteAllText(Path.Combine(Evidence,"balance-tests.json"),JsonUtility.ToJson(r,true));if(!r.passed)throw new Exception("Balance checks failed");}
    [Serializable] class BalanceResult{public bool passed,overBudgetBlocked,carryover,accounting;public int seeds=300,lowSales,normalSales,highSales,mildDrinks,hotDrinks,shortageMisses,fullMisses,excessWaste,shortageWaste,targetedProfit,maxOrderProfit;}


    public static void RefreshScene(){EditorSceneManager.OpenScene("Assets/Scenes/SmallKonbini.unity");var view=UnityEngine.Object.FindAnyObjectByType<StoreView>();view.materials[1].color=new Color(.86f,.82f,.68f);view.Build(new StoreSimulation(new ShopModel(42),42));var light=GameObject.Find("Sunlight").GetComponent<Light>();light.intensity=.8f;RenderSettings.ambientMode=UnityEngine.Rendering.AmbientMode.Flat;RenderSettings.ambientLight=new Color(.42f,.45f,.48f);AssetDatabase.SaveAssets();EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());}
    public static void BuildWeb(){RefreshScene();PlayerSettings.WebGL.compressionFormat=WebGLCompressionFormat.Disabled;PlayerSettings.WebGL.template="APPLICATION:Default";PlayerSettings.WebGL.initialMemorySize=128;var report=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{"Assets/Scenes/SmallKonbini.unity"},locationPathName="Build/Web",target=BuildTarget.WebGL,options=BuildOptions.None});File.Copy("Assets/Fonts/OFL.txt","Build/Web/FONT-LICENSE.txt",true);File.WriteAllText(Path.Combine(Evidence,"web-build-v4.json"),"{\"result\":\""+report.summary.result+"\",\"errors\":"+report.summary.totalErrors+",\"warnings\":"+report.summary.totalWarnings+",\"bytes\":"+report.summary.totalSize+",\"seconds\":"+report.summary.totalTime.TotalSeconds.ToString(System.Globalization.CultureInfo.InvariantCulture)+"}");if(report.summary.result!=BuildResult.Succeeded)throw new Exception("Web build failed");}
}






