const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.join(__dirname,'evidence'),read=name=>JSON.parse(fs.readFileSync(path.join(out,name),'utf8').replace(/^\uFEFF/,'')),data=read('staff-balance.json'),holdout=read('staff-holdout.json'),low=read('staff-low.json');
function group(rows,keys){const m=new Map();for(const r of rows){const k=keys.map(x=>r[x]).join('/');if(!m.has(k))m.set(k,[]);m.get(k).push(r);}return [...m].map(([key,rows])=>({key,rows}));}
const mean=(rows,key)=>rows.reduce((s,r)=>s+r[key],0)/rows.length;
const averages=group(data.cases,['weather','staff','price','policy']).map(g=>({weather:g.rows[0].weather,staff:g.rows[0].staff,price:g.rows[0].price,policy:g.rows[0].policy,n:g.rows.length,...Object.fromEntries(['revenue','sold','missed','waste','labor','profit'].map(k=>[k,mean(g.rows,k)]))}));
const pairs=group(averages,['weather','price','policy']).map(g=>({key:g.key,delta:g.rows.find(r=>r.staff===2).profit-g.rows.find(r=>r.staff===1).profit}));
const priceGroups=group(averages,['weather','staff','policy']);
const checks={staffOneWins:pairs.some(r=>r.delta<0),staffTwoWins:pairs.some(r=>r.delta>0),maxStockNotAlways:group(averages,['weather','staff','price']).some(g=>g.rows.some(r=>r.profit>g.rows.find(r=>r.policy===2).profit)),minStockNotAlways:group(averages,['weather','staff','price']).some(g=>g.rows.some(r=>r.profit>g.rows.find(r=>r.policy===0).profit)),price80NotAlways:priceGroups.some(g=>g.rows.some(r=>r.profit>g.rows.find(r=>r.price===0).profit)),price140NotAlways:priceGroups.some(g=>g.rows.some(r=>r.profit>g.rows.find(r=>r.price===3).profit)),labor:averages.every(r=>r.labor===(r.staff===1?600:2100))};
const summarize=rows=>group(rows,['weather','staff','price']).map(g=>({weather:g.rows[0].weather,staff:g.rows[0].staff,price:g.rows[0].price,n:g.rows.length,...Object.fromEntries(['revenue','sold','missed','waste','labor','profit'].map(k=>[k,mean(g.rows,k)]))}));
const h=summarize(holdout.cases),l=summarize(low.cases);checks.highDemandTwoWins=h.find(r=>r.weather===2&&r.staff===2).profit>h.find(r=>r.weather===2&&r.staff===1).profit;checks.lowSalesOneWins=l.find(r=>r.staff===1).profit>l.find(r=>r.staff===2).profit;
const result={passed:Object.values(checks).every(Boolean),count:data.count+holdout.count+low.count,matrixCount:data.count,holdoutCount:holdout.count,lowCount:low.count,checks,averages,pairs,representative:h,lowSales:l};
fs.writeFileSync(path.join(out,'staff-balance-summary.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.passed,count:result.count,checks,representative:result.representative},null,2));assert(result.passed,'Balance conditions failed');
